import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Navigation } from "@/components/navigation";
import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from '@clerk/themes'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "InternQuest",
    template: "%s | InternQuest",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: shadcn,
      layout: {
        socialButtonsPlacement: "bottom",
        unsafe_disableDevelopmentModeWarnings: true
      }
    }}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <main className="min-h-screen flex flex-col">
            <Navigation/>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
