#!/usr/bin/env node

/**
 * Setup Neon Test Database Branch
 * 
 * This script creates a Neon database branch for testing.
 * The branch is created from the main branch and includes all schema/data.
 * 
 * Usage: pnpm test:db:setup
 */

import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join } from 'path';

const BRANCH_NAME = 'test';
const ENV_TEST_FILE = '.env.test';

async function setupTestBranch() {
  console.log('🔧 Setting up Neon test database branch...\n');

  try {
    // Check if branch already exists
    console.log('📋 Checking for existing test branch...');
    let branchExists = false;
    
    try {
      const branches = execSync('neonctl branches list --output json', {
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe']
      });
      
      const branchList = JSON.parse(branches);
      branchExists = branchList.some((b) => b.name === BRANCH_NAME);
    } catch (error) {
      console.log('⚠️  Could not check existing branches, will try to create new one');
    }

    let connectionString;

    if (branchExists) {
      console.log(`✅ Test branch '${BRANCH_NAME}' already exists`);
      
      // Get connection string for existing branch
      const branchInfo = execSync(`neonctl branches get ${BRANCH_NAME} --output json`, {
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe']
      });
      
      const branch = JSON.parse(branchInfo);
      connectionString = branch.connection_uris?.[0]?.connection_uri;
      
      if (!connectionString) {
        throw new Error('Could not retrieve connection string from existing branch');
      }
    } else {
      console.log(`🌿 Creating new test branch '${BRANCH_NAME}'...`);
      
      // Create a new branch from main/primary
      const createOutput = execSync(`neonctl branches create --name ${BRANCH_NAME} --output json`, {
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe']
      });
      
      const newBranch = JSON.parse(createOutput);
      connectionString = newBranch.connection_uris?.[0]?.connection_uri;
      
      if (!connectionString) {
        throw new Error('Could not retrieve connection string from new branch');
      }
      
      console.log('✅ Test branch created successfully');
    }

    // Write to .env.test file
    console.log(`📝 Writing connection string to ${ENV_TEST_FILE}...`);
    const envContent = `# Neon Test Database Branch
# Auto-generated by test:db:setup script
# DO NOT commit this file to version control

TEST_DATABASE_URL=${connectionString}
`;
    
    writeFileSync(join(process.cwd(), ENV_TEST_FILE), envContent);
    
    console.log('\n✅ Test database setup complete!');
    console.log(`\n📌 Test branch: ${BRANCH_NAME}`);
    console.log(`📌 Connection string saved to: ${ENV_TEST_FILE}`);
    console.log('\n💡 You can now run tests with: pnpm test');
    console.log('💡 To clean up, run: pnpm test:db:teardown\n');
    
  } catch (error) {
    console.error('\n❌ Error setting up test database:');
    console.error(error.message);
    console.error('\n💡 Make sure you have:');
    console.error('   1. neonctl installed: npm install -g neonctl');
    console.error('   2. Logged in: neonctl auth');
    console.error('   3. A Neon project configured\n');
    process.exit(1);
  }
}

setupTestBranch();
